version: "3.3"
services:
  postgresdb:
    image: postgres:11.10
    restart: on-failure
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres