# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRE_URL}
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PWD}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
    generate-ddl: true
  # Spring security
  security:
    user:
      name: monitor
      password: fCwfHpjhDeV5s5jZ
      roles: ACTUATOR
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080
# Health indicators
management.endpoint.health:
  roles: ACTUATOR
  show-details: always
management.health.db.enabled: true
