package cz.loono.backend.api.dto

enum class ExaminationTypeDTO {
    GENERAL_PRACTITIONER,
    DENTIST,
    GYNECOLOGIST,
    UROLOGIST,
    DERMATOLOGIST,
    OPHTHALMOLOGIST,
    TOKS,
    COLONOSCOPY,
    MAMMOGRAM,
    VENEREAL_DISEASES,
    ULTRASOUND_BREAST,
    TESTICULAR_SELF,
    BREAST_SELF
}
