# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRE_URL}
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PWD}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    generate-ddl: true
    open-in-view: true
  # Throw 404 when no request handler can be found
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: WARN
    cz.loono.backend: INFO
    org.springframework: WARN
    org.hibernate: WARN
# Server configuration
server:
  port: 8080
  error.path: "/error"
# Health indicators
management.endpoint.health.show-details: always
management.health:
  db.enabled: true
  diskspace.enabled: false
scheduler.cron:
  daily-task: "0 0 3 * * ?"
  data-update: "0 0 2 2 * ?"

task.badge-downgrade:
  page-size: 100
  tolerance-months: 0
