name: 'Build and Test'

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Set up JDK 17'
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Gradle
        env:
          ONESIGNAL_API_KEY: ${{ secrets.ONESIGNAL_API_KEY }}
        run: |
          ./gradlew build -x ktlintMainSourceSetCheck 

      - name: Publish Unit Test Results
        # This action shall be used for ubuntu
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          report_individual_runs: true
          files: backend/build/test-results/**/*.xml
