name: Master branch CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Build with Gradle
        run: ./gradlew build
