name: 'Post deploy tests'

on:
  workflow_run:
    workflows: ["Deploy backend to ECS"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep for 30 seconds to waiting for the server start
        run: sleep 30s
        shell: bash
        
      # Healthcheck
      - name: Healthcheck request
        id: check
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://loono.ceskodigital.net/actuator/health"
          method: 'GET'
      - name: Healthcheck values
        id: checkval
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.check.outputs.response }}
          status: "status"
          db: "components.db.status"
          ping: "components.ping.status"
      - name: Healthcheck evaluation
        if: ${{ steps.checkval.outputs.status }} != "UP" || ${{ steps.checkval.outputs.db }} != "UP" || ${{ steps.checkval.outputs.ping }} != "UP"
        run: |
          echo "Healthcheck status is not UP!"
          exit 1
