name: 'Post deploy tests'

on:
  workflow_run:
    workflows: ["Deploy backend to ECS"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: Healthcheck request
        id: check
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://loono.ceskodigital.net/actuator/health"
          method: 'GET'
      - name: Healthcheck values
        id: checkval
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.check.outputs.response }}
          status: "status"
          db: "components.db.status"
          ping: "components.ping.status"
      - name: Show Response
        run: echo "${{ steps.checkval.outputs.status }} ${{ steps.checkval.outputs.db }} ${{ steps.checkval.outputs.ping }}"
