name: 'Post deploy tests'

on:
  workflow_run:
    workflows: ["Deploy backend to ECS"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: Health check
        id: check
        uses: fjogeleit/http-request-action@master
        with:
          method: 'GET'
          url: "https://loono.ceskodigital.net/actuator/health"
      - name: Show Response
        run: echo ${{ steps.check.outputs.response }}
