name: 'Post deploy tests'

on:
  workflow_run:
    workflows: ["Deploy backend to ECS"]
    types:
      - completed

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sleep for 10 minutes to waiting for the server start
        run: sleep 600s
        shell: bash
        
      # Healthcheck
      - name: Healthcheck request
        id: check
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://loono.ceskodigital.net/actuator/health"
          method: 'GET'
      - name: Healthcheck values
        id: checkval
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.check.outputs.response }}
          status: "status"
          db: "components.db.status"
          ping: "components.ping.status"
          uptime: "components.uptimeMetric.details.Server uptime"
      - name: Healthcheck evaluation
        if: steps.checkval.outputs.status != 'UP' || steps.checkval.outputs.db != 'UP' || steps.checkval.outputs.ping != 'UP' || steps.checkval.outputs.uptime > 900000
        run: |
          echo ${{ steps.checkval.outputs.uptime }} | ${{ steps.checkval.outputs.uptime > 300000 }}
          echo "Healthcheck status is not UP or the version is the old one!"
          exit 1

      # OpenAPI documentation
      - name: OpenAPI documentation request
        id: doc
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://loono.ceskodigital.net/v3/api-docs"
          method: 'GET'
      - name: OpenAPI documentation values
        id: docval
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.doc.outputs.response }}
          title: "info.title"
      - name: OpenAPI documentation evaluation
        if: steps.docval.outputs.title != 'The Loono API'
        run: |
          echo "API documentation is not available!"
          exit 1
